### PR TITLE
Bluetooth Animation added 

### PR DESCRIPTION
**Pull request by aaryankotharii**
Added bluetooth animation to tutorials.
similar to the success and reject buttons present but with pulsating layer.
preview :
bluetooth

### CODE REVIEW

**Comment by wazowski78** [comment]
Please, a WiFi similar animation please!

**Comment by aaryankotharii** [comment]
sure👍🏻

**Comment by aaryankotharii** [comment]
Fetch upstream dev ✅

**Comment by Shubham0812** [comment]
Merged! 😄

**Pull request merged**
